#!/usr/bin/env bash
# Write or remove Configs/signing.local.xcconfig so xcodegen / xcodebuild can
# pick up the local development identity when it exists.
#
# Used as project.yml's preGenCommand and by Scripts/bootstrap.sh after the
# identity is created. Missing identity is success: Mac targets stay ad-hoc.
# CALLNOTES_LOCAL_SIGNING=0 forces the ad-hoc overlay off even if the identity
# is in the keychain.
#
# Sourced by Scripts/bootstrap.sh for the shared identity name and presence
# check. When sourced, this file only defines helpers and does not write files.
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
  set -euo pipefail
fi

CALLNOTES_LOCAL_SIGNING_NAME="CallNotes Local Signing"

callnotes_local_signing_identity_present() {
  security find-identity -v -p codesigning 2>/dev/null | grep -F "\"$CALLNOTES_LOCAL_SIGNING_NAME\"" >/dev/null
}

if [[ "${BASH_SOURCE[0]}" != "${0}" ]]; then
  return 0
fi

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
LOCAL_XCCONFIG="$ROOT/Configs/signing.local.xcconfig"

apply_disabled() {
  case "${CALLNOTES_LOCAL_SIGNING:-}" in
    0|false|FALSE|no|NO) return 0 ;;
    *) return 1 ;;
  esac
}

remove_overlay() {
  rm -f "$LOCAL_XCCONFIG"
}

write_overlay() {
  mkdir -p "$ROOT/Configs"
  cat > "$LOCAL_XCCONFIG" <<EOF
// Generated by Scripts/sync-local-signing.sh. Gitignored. Do not commit.
// Local development identity only - cannot notarize or distribute.
CODE_SIGN_STYLE = Manual
CODE_SIGN_IDENTITY = $CALLNOTES_LOCAL_SIGNING_NAME
DEVELOPMENT_TEAM =
OTHER_CODE_SIGN_FLAGS = --timestamp=none
// Hardened runtime enforces library validation, which requires a Team ID on
// the process and every library it loads. This identity has none
// (TeamIdentifier=not set), so the app's own embedded SPM dylib fails the
// match and dyld aborts before main. Xcode already disables hardened runtime
// for ad-hoc signing; do the same here. Release/notarization signing is
// Scripts/release/build-dmg.sh (--options runtime), not this overlay.
ENABLE_HARDENED_RUNTIME = NO
EOF
}

if apply_disabled; then
  remove_overlay
  printf 'local signing: disabled via CALLNOTES_LOCAL_SIGNING (ad-hoc)\n'
  exit 0
fi

if callnotes_local_signing_identity_present; then
  write_overlay
  printf 'local signing: applying "%s" -> Configs/signing.local.xcconfig\n' "$CALLNOTES_LOCAL_SIGNING_NAME"
  exit 0
fi

remove_overlay
printf 'local signing: no "%s" identity; leaving ad-hoc\n' "$CALLNOTES_LOCAL_SIGNING_NAME"
