#!/usr/bin/env bash
# Write or remove Configs/signing.local.xcconfig so xcodegen / xcodebuild can
# pick up the local development identity when it exists.
#
# Used as project.yml's preGenCommand and by Scripts/bootstrap.sh after the
# identity is created. Missing identity is success: Mac targets stay ad-hoc.
# CALLNOTES_LOCAL_SIGNING=0 forces the ad-hoc overlay off even if the identity
# is in the keychain.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
CERT_NAME="CallNotes Local Signing"
LOCAL_XCCONFIG="$ROOT/Configs/signing.local.xcconfig"

identity_present() {
  security find-identity -v -p codesigning 2>/dev/null | grep -F "\"$CERT_NAME\"" >/dev/null
}

apply_disabled() {
  case "${CALLNOTES_LOCAL_SIGNING:-}" in
    0|false|FALSE|no|NO) return 0 ;;
    *) return 1 ;;
  esac
}

remove_overlay() {
  rm -f "$LOCAL_XCCONFIG"
}

write_overlay() {
  mkdir -p "$ROOT/Configs"
  cat > "$LOCAL_XCCONFIG" <<EOF
// Generated by Scripts/sync-local-signing.sh. Gitignored. Do not commit.
// Local development identity only - cannot notarize or distribute.
CODE_SIGN_STYLE = Manual
CODE_SIGN_IDENTITY = $CERT_NAME
DEVELOPMENT_TEAM =
OTHER_CODE_SIGN_FLAGS = --timestamp=none
EOF
}

if apply_disabled; then
  remove_overlay
  printf 'local signing: disabled via CALLNOTES_LOCAL_SIGNING (ad-hoc)\n'
  exit 0
fi

if identity_present; then
  write_overlay
  printf 'local signing: applying "%s" -> Configs/signing.local.xcconfig\n' "$CERT_NAME"
  exit 0
fi

remove_overlay
printf 'local signing: no "%s" identity; leaving ad-hoc\n' "$CERT_NAME"
